import * as React from "react";

const iconMap = {
  group: require("./icons/group.svg"),
  oval: require("./icons/oval.svg"),
  Polygon: require("./icons/Polygon.svg"),
  triangle: require("./icons/tringle.svg"),
  star_icon: require("./icons/star_icon.svg"),
  insert: require("./icons/insert.svg"),
  symbol: require("./icons/symbol.svg"),
  download: require("./icons/download.svg"),
  export: require("./icons/export.svg"),
  menu: require("./icons/menu.svg"),
  icon: require("./icons/icon.svg"),
  "icon-cursor": require("./icons/icon_cursor.svg"),
  "right-arrow": require("./icons/right_arrow.svg"),
  artboard: require("./icons/Artboard.svg"),
  "icon-close": require("./icons/icon_close.svg"),
  "drop-menu": require("./icons/drop_menu.svg"),
  "color-drag": require("./icons/ColorDrag.svg"),
  "color-picker": require("./icons/Colorpicker.svg"),
  "double-arrow": require("./icons/doublearrow.svg"),
  "align-bottom": require("./icons/align-bottom.svg"),
  "align-center": require("./icons/align-center.svg"),
  "align-left": require("./icons/align-left.svg"),
  "align-right": require("./icons/align-right.svg"),
  "align-top": require("./icons/align-top.svg"),
  "align-justify": require("./icons/align-justify.svg"),
  "align-vertically-center": require("./icons/align-vertically-center.png"),
  "distribute-horizontal": require("./icons/distribute-horizontal.svg"),
  "distribute-vertically": require("./icons/distribute-vertically.svg"),
  "flexlayout-align-align-baseline": require("./icons/flexlayout-align-align-baseline.svg"),
  "flexlayout-horizontal-align-center": require("./icons/flexlayout-horizontal-align-center.svg"),
  "flexlayout-horizontal-reverse-alignbaseline": require("./icons/flexlayout-horizontal-reverse-alignbaseline.svg"),
  "flexlayout-reverse-alignbaseline": require("./icons/flexlayout-reverse-alignbaseline.svg"),
  "flexlayout-reverse-alignstart": require("./icons/flexlayout-reverse-alignstart.svg"),
  "flexlayout-reverse-alignend": require("./icons/flexlayout-reverse-alignend.svg"),
  "flexlayout-reverse-aligncenter": require("./icons/flexlayout-reverse-aligncenter.svg"),
  "flexlayout-horizontal-reverse-alignend": require("./icons/flexlayout-horizontal-reverse-alignend.svg"),
  "flexlayout-horizontal-reverse-alignstart": require("./icons/flexlayout-horizontal-reverse-alignstart.svg"),
  "flexlayout-horizontal-reverse-aligncenter": require("./icons/flexlayout-horizontal-reverse-aligncenter.svg"),
  "flexlayout-align-center": require("./icons/flexlayout-align-center.svg"),
  "flexlayout-align-end": require("./icons/flexlayout-align-end.svg"),
  "flexlayout-align-start": require("./icons/flexlayout-align-start.svg"),
  "flexlayout-align-stretch": require("./icons/flexlayout-align-stretch.svg"),
  "flexlayout-vertical-end": require("./icons/flexlayout-vertical-end.svg"),
  "flexlayout-vertical-justify-center": require("./icons/flexlayout-vertical-justify-center.svg"),
  "flexlayout-vertical-start": require("./icons/flexlayout-vertical-start.svg"),
  "flexlayout-vertical-spacearound": require("./icons/flexlayout-spacearound.svg"),
  "flexlayout-vertical-spacebetween": require("./icons/flexlayout-spacebetween.svg"),
  "flexlayout-justify-spacebetween": require("./icons/flexlayout-justify-spacebetween.svg"),
  "flexlayout-justify-spacearound": require("./icons/flexlayout-justify-spacearound.svg"),
  "flexlayout-baseline": require("./icons/flexlayout-baseline.svg"),
  "flexlayout-start": require("./icons/flexlayout-start.svg"),
  "flexlayout-end": require("./icons/flexlayout-end.svg"),
  "flexlayout-justify": require("./icons/flexlayout-justify.svg"),
  "flexlayout-center": require("./icons/flexlayout-center.svg"),
  "flexlayout-spacebetween": require("./icons/flexlayout-spacebetween.svg"),
  "flexlayout-spacearound": require("./icons/flexlayout-spacearound.svg"),
  "flexlayout-bottom": require("./icons/flexlayout-bottom.svg"),
  "flexlayout-top": require("./icons/flexlayout-top.svg"),
  "flexitem-selfstart": require("./icons/flexitem-selfstart.svg"),
  "flexitem-selfcenter": require("./icons/flexitem-selfcenter.svg"),
  "flexitem-selfend": require("./icons/flexitem-selfend.svg"),
  "flexitem-selfstretch": require("./icons/flexitem-selfstretch.svg"),
  "flexitem-selfbaseline": require("./icons/flexitem-selfbaseline.svg"),
  // "flexitem-selfbaseline": require("./icons/flexitem-selfbaseline.svg"),

  flip1: require("./icons/flip1.svg"),
  flip2: require("./icons/flip2.svg"),
  "mirror-horizontally": require("./icons/mirror-horizontally.svg"),
  "rectangle-shape": require("./icons/rectangle-shape.svg"),
  image: require("./icons/image.svg"),
  lock: require("./icons/lock.svg"),
  document: require("./icons/icon_document.svg"),
  warning: require("./icons/icon_warning.svg"),
  mirror: require("./icons/mirror.svg"),
  text: require("./icons/text.svg"),
  bold: require("./icons/bold.svg"),
  close: require("./icons/close.svg"),
  crop: require("./icons/crop.svg"),
  cog: require("./icons/setting.svg"),
  uparrow: require("./icons/uparrow.svg"),
  downarrow: require("./icons/downarrow.svg"),
  folder: require("./icons/folder.svg"),
  pencil: require("./icons/pencil.svg"),
  paint: require("./icons/paint.svg"),
  zoom: require("./icons/zoom.svg"),
  zoomout: require("./icons/zoomout.svg"),
  unlock: require("./icons/unlock.svg"),
  zoomin: require("./icons/zoomin.svg"),
  uploadimg: require("./icons/icon_uploadimg.svg"),
  confirm: require("./icons/icon_confirm.svg"),
  center: require("./icons/icn_center.svg"),
  contain: require("./icons/icn_contain.svg"),
  cover: require("./icons/icn_cover.svg"),
  repeat: require("./icons/icn_repeat.svg"),
  stretch: require("./icons/icn_stretch.svg"),
  "letter-spacing": require("./icons/letter-spacing.svg"),
  "line-spacing": require("./icons/line-spacing.svg"),
  "paragraph-spacing": require("./icons/paragraph-spacing.svg"),
  "icon-underline": require("./icons/icon_underline.svg"),
  "icon-transform": require("./icons/icon_Transform.svg"),
  "layout-vertical": require("./icons/icon_layout1.svg"),
  "layout-horizontal": require("./icons/icon_layout2.svg")
};

export default class Icon extends React.Component<any, any> {
  render() {
    // console.log(this.props.name, iconMap[this.props.name], "iconName");
    return (
      <img
        src={this.props.name ? iconMap[this.props.name] : iconMap["group"]}
        width={this.props.size ? this.props.size : 32}
        height={this.props.size ? this.props.size : 32}
        style={{
          border: "none",
          marginRight: this.props.marginRight ? 5 : 0,
          marginLeft: this.props.marginLeft ? 5 : 0
        }}
        {...this.props}
      />
    );
  }
}
